# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mantis/v1/mantis_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'mantis/v1/mantis_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.api import client_pb2 as google_dot_api_dot_client__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import mantis_core_pb2 as mantis_dot_v1_dot_mantis__core__pb2
from ... import registry_pb2 as registry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1emantis/v1/mantis_service.proto\x12\x0emantis.service\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1bmantis/v1/mantis_core.proto\x1a\x0eregistry.protoBa\n\x15\x63om.mantis.service.v1B\rMantisServiceP\x01Z#google.golang.org/mantis/service/v1\xaa\x02\x11Mantis.Service.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mantis.v1.mantis_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.mantis.service.v1B\rMantisServiceP\001Z#google.golang.org/mantis/service/v1\252\002\021Mantis.Service.V1'
# @@protoc_insertion_point(module_scope)
