# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mantis/v1/mantis_persona.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'mantis/v1/mantis_persona.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1emantis/v1/mantis_persona.proto\x12\x11mantis.persona.v1\"\xde\x01\n\x16PersonaCharacteristics\x12\x17\n\x0f\x63ore_principles\x18\x01 \x03(\t\x12\x1a\n\x12\x64\x65\x63ision_framework\x18\x02 \x01(\t\x12\x1b\n\x13\x63ommunication_style\x18\x03 \x01(\t\x12\x19\n\x11thinking_patterns\x18\x04 \x03(\t\x12\x1e\n\x16\x63haracteristic_phrases\x18\x05 \x03(\t\x12\x1d\n\x15\x62\x65havioral_tendencies\x18\x06 \x03(\t\x12\x18\n\x10original_content\x18\x07 \x01(\t\"\x88\x01\n\x0eRoleAdaptation\x12\x14\n\x0cleader_score\x18\x01 \x01(\x02\x12\x16\n\x0e\x66ollower_score\x18\x02 \x01(\x02\x12\x16\n\x0enarrator_score\x18\x03 \x01(\x02\x12\x16\n\x0epreferred_role\x18\x04 \x01(\t\x12\x18\n\x10role_flexibility\x18\x05 \x01(\x02\"\xdd\x01\n\x10\x43ompetencyScores\x12T\n\x11\x63ompetency_scores\x18\x01 \x03(\x0b\x32\x39.mantis.persona.v1.CompetencyScores.CompetencyScoresEntry\x12:\n\x0frole_adaptation\x18\x02 \x01(\x0b\x32!.mantis.persona.v1.RoleAdaptation\x1a\x37\n\x15\x43ompetencyScoresEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"z\n\x0f\x44omainExpertise\x12\x17\n\x0fprimary_domains\x18\x01 \x03(\t\x12\x19\n\x11secondary_domains\x18\x02 \x03(\t\x12\x15\n\rmethodologies\x18\x03 \x03(\t\x12\x1c\n\x14tools_and_frameworks\x18\x04 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mantis.v1.mantis_persona_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPETENCYSCORES_COMPETENCYSCORESENTRY']._loaded_options = None
  _globals['_COMPETENCYSCORES_COMPETENCYSCORESENTRY']._serialized_options = b'8\001'
  _globals['_PERSONACHARACTERISTICS']._serialized_start=54
  _globals['_PERSONACHARACTERISTICS']._serialized_end=276
  _globals['_ROLEADAPTATION']._serialized_start=279
  _globals['_ROLEADAPTATION']._serialized_end=415
  _globals['_COMPETENCYSCORES']._serialized_start=418
  _globals['_COMPETENCYSCORES']._serialized_end=639
  _globals['_COMPETENCYSCORES_COMPETENCYSCORESENTRY']._serialized_start=584
  _globals['_COMPETENCYSCORES_COMPETENCYSCORESENTRY']._serialized_end=639
  _globals['_DOMAINEXPERTISE']._serialized_start=641
  _globals['_DOMAINEXPERTISE']._serialized_end=763
# @@protoc_insertion_point(module_scope)
