# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import mantis_prompt_pb2 as mantis_dot_v1_dot_mantis__prompt__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mantis/v1/mantis_prompt_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PromptCompositionServiceStub(object):
    """DEPRECATED: Complex prompt composition replaced with simple ContextualPrompt assembly
    This service is maintained for backward compatibility only
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComposePrompt = channel.unary_unary(
                '/mantis.prompts.PromptCompositionService/ComposePrompt',
                request_serializer=mantis_dot_v1_dot_mantis__prompt__pb2.PromptCompositionRequest.SerializeToString,
                response_deserializer=mantis_dot_v1_dot_mantis__prompt__pb2.PromptCompositionResponse.FromString,
                _registered_method=True)
        self.GetCapabilities = channel.unary_unary(
                '/mantis.prompts.PromptCompositionService/GetCapabilities',
                request_serializer=mantis_dot_v1_dot_mantis__prompt__pb2.PromptCapabilitiesRequest.SerializeToString,
                response_deserializer=mantis_dot_v1_dot_mantis__prompt__pb2.PromptCapabilitiesResponse.FromString,
                _registered_method=True)


class PromptCompositionServiceServicer(object):
    """DEPRECATED: Complex prompt composition replaced with simple ContextualPrompt assembly
    This service is maintained for backward compatibility only
    """

    def ComposePrompt(self, request, context):
        """DEPRECATED: Use ContextualPrompt for simple template assembly instead
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapabilities(self, request, context):
        """DEPRECATED: Simple template assembly no longer requires complex capabilities
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PromptCompositionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComposePrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.ComposePrompt,
                    request_deserializer=mantis_dot_v1_dot_mantis__prompt__pb2.PromptCompositionRequest.FromString,
                    response_serializer=mantis_dot_v1_dot_mantis__prompt__pb2.PromptCompositionResponse.SerializeToString,
            ),
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=mantis_dot_v1_dot_mantis__prompt__pb2.PromptCapabilitiesRequest.FromString,
                    response_serializer=mantis_dot_v1_dot_mantis__prompt__pb2.PromptCapabilitiesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mantis.prompts.PromptCompositionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mantis.prompts.PromptCompositionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PromptCompositionService(object):
    """DEPRECATED: Complex prompt composition replaced with simple ContextualPrompt assembly
    This service is maintained for backward compatibility only
    """

    @staticmethod
    def ComposePrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mantis.prompts.PromptCompositionService/ComposePrompt',
            mantis_dot_v1_dot_mantis__prompt__pb2.PromptCompositionRequest.SerializeToString,
            mantis_dot_v1_dot_mantis__prompt__pb2.PromptCompositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mantis.prompts.PromptCompositionService/GetCapabilities',
            mantis_dot_v1_dot_mantis__prompt__pb2.PromptCapabilitiesRequest.SerializeToString,
            mantis_dot_v1_dot_mantis__prompt__pb2.PromptCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
